appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: nNkRqpzSdmX+urJ7l5aNKoKoZq8wggZEYfNtHoYK3f8bTwaunSCPOx3DrRejbz1I6oMi7SQqd9RkpAhwxFiihOL6dY5xKLbTwyL9RJkVa6smfwm7BuXXsn/Oq1qF9CxhIkqYUUA3Sg4Mt5KBwlzd89eDRBd78Fz4woEzc+kHLyF9Yg6zBgcB9jzWWhyxE4NIt602BWbN5NuL7e8YFEsmuVmF04ZmatvuQZbi8J9yD3bY2vUbdUWHh7HwQi66j8LUtXt+xPoy3FJQa30JPMo6rvSSPVWl3MwWRJnUwX29RWsv7a5JLHrAmnRYrkxJxo2emgEn1X97EA+tZ6ChpRmLK9H+za2nIExs2OqlpEU9A7Asu31WUS3QBy9CNMYGjc43AhJQYT4a2Jy5mg2cOmCKtCH5dYumKDUZCGoZV63rp3ZKmEprYUsnoU+5oY6YewuN1EfJRlvPzYAnn7E76OGQ08TwfLHL7lkKWW6qwLDNzEUKdm1Bykb6akLS6+IKF0UR8aOVy3dQMfOz8ylHOd80wSedrgSEvUef64ZYP/SLXHNeytIqk3TA3E6OGdfBAM9ab4zdEFd+rVG/sxkNJVml50OGroi7ydBV3Bf9fLdPUK4Zf3NBG4lqRVRDuxl70+UqR1bo+a//48t2amjvwB7mwmRzrD3ScDLZHtFGeEoUFgI=}
